title: Task Saver
author: Remilekun Elijah
email: mailto:Remilekunelijah21997@gmail.com
description: Task saver | To Do app | catch up with your task easily

github_username: github.com/Remilekun-Elijah
facebook_username: fb.com/Remilekun Elijah JNr

show_excerpts: true 
theme: jekyll-theme-slate
